/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_ZERO_CACHE_URL: string
  readonly VITE_AUTH_ISSUER_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}